Repository pinecone-studio/pinecone-intern-monorepo-2, pull requests merged in 2024-12, with the labels that each got.

#302 feat: fix
  .github/workflows/ci.yml
Labels: PR status: code ready

#293 feat: attraction backend
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/update-attraction.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/update-user.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/update-attraction.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#312 feat(concert-ticket-booking): event priority update
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/create-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/update-event-priority.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/update-event-priority.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready

#315 feat(tinder-backend): forgetpass checkmail
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/check-email.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/check-email.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#304 feat: added resen otp's mutation and jest then fixed the issues
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/register-email-flow.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/resend-otp.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/verify-otp-flow.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/create-token-cookie.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/existingEmail.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/generateOtp.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/otp-expiration.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/sendOtp.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/resend-otp.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/verify-otp.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/utils/user/check-otp-expiration.ts
  apps/1CD/tinder/backend/src/utils/user/create-token-cookie.ts
  apps/1CD/tinder/backend/src/utils/user/send-otp-email.ts
Labels: PR status: code ready

#320 297 leave request create new request backend
  apps/1CD/leave-request/backend/specs/resolvers/mutations/request/create-request.spec.ts
  apps/1CD/leave-request/backend/src/models/index.ts
  apps/1CD/leave-request/backend/src/models/request.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/index.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/request/create-request.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/request/index.ts
  apps/1CD/leave-request/backend/src/schemas/index.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
  apps/1CD/leave-request/backend/src/utils/check-token.ts
Labels: PR status: code ready

#316 246 frontend search result
  apps/1CD/hotel-booking/frontend/cypress/e2e/select-adult.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/project.json
  apps/1CD/hotel-booking/frontend/specs/components/search-results/DatePicker.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/SearchResSection.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/SearchedHotelCards.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/TravelerSelection.tsx
  apps/1CD/hotel-booking/frontend/src/app/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/DatePicker.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/SearchResult.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/SearchedHotelCards.tsx
Labels: PR status: code ready

#272 feat: added otp page
  apps/1CD/tinder/frontend/cypress/e2e/(public)/register/email/register-email.cy.tsx
  apps/1CD/tinder/frontend/cypress/support/commands.ts
  apps/1CD/tinder/frontend/cypress/support/e2e.ts
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/cypress/utils/intercept-graphql.ts
  apps/1CD/tinder/frontend/project.json
  apps/1CD/tinder/frontend/src/app/(public)/register/email/page.tsx
  apps/1CD/tinder/frontend/src/graphql/user/register.graphql
  libs/shadcn/src/lib/ui/sonner.tsx
Labels: PR status: code ready

#333 forget pass and verify pass iin backendiig zasvarlav
  apps/1CD/instagram/backend/src/resolvers/mutations/auth/verify-newpass.ts
  apps/1CD/instagram/backend/src/schemas/user.schema.ts
Labels: PR status: code ready

#337 feat: fix ci
  .github/workflows/ci.yml
Labels: PR status: code ready

#341 feat: fix cd
  .github/workflows/cd.yml
Labels: PR status: code ready

#342 forget pass uurchlult zuvhun backended
  apps/1CD/instagram/backend/src/schemas/user.schema.ts
Labels: PR status: code ready

#344 fix(backend): bagshiin uurchlultiig oruulsan
  apps/1CD/instagram/backend/src/resolvers/mutations/comment/create-comment.ts
Labels: PR status: code ready

#346 fix(backend): forget passwordad backend uurchlult oruulav
  apps/1CD/instagram/backend/src/resolvers/mutations/auth/forget-password.ts
Labels: PR status: code ready

#331 feat(concert-backend): ordering ticket
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/create-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/add-to-cart.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/delete-order.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/order/get-order.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/models/order.model.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/add-to-cart.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/delete-order.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/order/get-order.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/order/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/order.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/ticket.schema.ts
Labels: PR status: code ready

#352 feat(hotel-booking-backend): get one hotel backend is done
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/hotel/get-hotel.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/hotels/get-hotel.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/hotels/index.ts
Labels: PR status: code ready

#353 288 (hotel booking frontend) using mockdata booking
  apps/1CD/hotel-booking/frontend/cypress/e2e/(main)/home-page.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/add-hotel/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/checkout/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/next.config.js
  apps/1CD/hotel-booking/frontend/specs/components/BookingInformation.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/BookingRightSide.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/SelectCountry.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/StarsStaticJson.spec.ts
  apps/1CD/hotel-booking/frontend/specs/components/WhoCheckingText.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/checkout/BookingErrorMessages.tsx
  apps/1CD/hotel-booking/frontend/src/app/checkout/BookingInformationInput.tsx
  apps/1CD/hotel-booking/frontend/src/app/checkout/CardInformation.tsx
  apps/1CD/hotel-booking/frontend/src/app/checkout/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingImportantInformation.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingPageRightSide.tsx
  apps/1CD/hotel-booking/frontend/src/components/Header.tsx
  apps/1CD/hotel-booking/frontend/src/components/SelectCountry.tsx
  apps/1CD/hotel-booking/frontend/src/components/StarsStaticJson.tsx
  apps/1CD/hotel-booking/frontend/src/components/WhoChecking.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
  apps/1CD/tinder/frontend/.nycrc
Labels: PR status: code ready

#359 270 hotel booking frontend homepage
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/HomePage.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/specs/components/HomePageCard.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/HomePageCard.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#360 feat: [tinder]:fixed the mockuser for cypress
  .vscode/settings.json
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/verify-otp-flow.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/generateOtp.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/sendOtp.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/check-email.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/register-with-email.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/resend-otp.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/utils/user/check-existing-email.ts
  apps/1CD/tinder/backend/src/utils/user/check-otp-expiration.ts
  apps/1CD/tinder/backend/src/utils/user/create-token-cookie.ts
  apps/1CD/tinder/backend/src/utils/user/generate-otp.ts
  apps/1CD/tinder/backend/src/utils/user/send-otp-email.ts
Labels: PR status: code ready

#363 feat: added in user index
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
Labels: PR status: code ready

#364 feat(hotel-booking frontend): homePage Cypress hiij uzev
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/HomePage.cy.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
Labels: PR status: code ready

#374 fix(backedn): schema deer yum uurchilsun
  apps/1CD/instagram/backend/src/schemas/user.schema.ts
Labels: PR status: code ready, backend

#375 feat: tinder:fixed env
  apps/1CD/tinder/backend/project.json
Labels: PR status: code ready

#377 feat: tinder:console in back to cd
  apps/1CD/tinder/backend/src/utils/user/send-otp-email.ts
Labels: PR status: code ready

#381 feat: tinder:fixed the backend sting of otp and added console in node…
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/check-email.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/register-email-flow.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/resend-otp.spec.ts
  apps/1CD/tinder/backend/src/models/user/user.model.ts
Labels: PR status: code ready

#380 feat(concert-backend): ticket cancel mutation
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/ticket-cancel/ticket-cancel.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/ticket.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/category/get-category.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/models/order.model.ts
  apps/1CD/concert-ticket-booking/backend/src/models/request.model.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/ticket-cancel/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/ticket-cancel/ticket-cancel.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/ticket/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/ticket/ticket.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/category/get-category.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/category.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/ticket.schema.ts
Labels: PR status: code ready, backend

#385 384 nest config
  apps/1CD/instagram/backend/next.config.js
Labels: PR status: code ready, backend, instagram

#389 feat: fix ci
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  apps/example/frontend/src/components/Container.tsx
Labels: PR status: code ready

#391 next config inbackend
  apps/1CD/instagram/backend/next.config.js
Labels: PR status: code ready, backend

#399 382 tinderotp frontend last 1
  apps/1CD/tinder/backend/next.config.js
Labels: PR status: code ready

#405 feat(hotel-booking-backend): cd prod
  apps/1CD/hotel-booking/backend/src/models/booking.model.ts
Labels: PR status: code ready

#406 feat(fixed the backend of email): f
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/check-email.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/create-token-cookie.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/existingEmail.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/otp-expiration.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/sendOtp.spec.ts
  apps/1CD/tinder/backend/src/utils/user/check-existing-email.ts
Labels: PR status: code ready

#397 feat(hotel-booking-backend-gerrooms): getroom-data,getroom-service
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/hotel-detail.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/hotel-service.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/hotel-detail.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/hotel-service.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#419 feat(hotel-booking-backend-update-images): hotel-booking-backend-upda…
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/hotel/update-hotel-images.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/update-hotel-images.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
Labels: PR status: code ready

#411 12 tinder birthday backend
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/birthday.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/register-email-flow.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/birthday.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/register-with-email.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#422 feat(hotel-booking-backend): get rooms done
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/models/rooms.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/add-amenity.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready, backend

#425 add env to config file
  apps/1CD/instagram/frontend/next.config.js
Labels: PR status: code ready

#415 navbar 20% done
  apps/1CD/instagram/frontend/cypress/utils/all-pages.json
  apps/1CD/instagram/frontend/public/images/img.avif
  apps/1CD/instagram/frontend/specs/components/SuggestUser.tsx
  apps/1CD/instagram/frontend/specs/components/header/Header.spec.tsx
  apps/1CD/instagram/frontend/specs/components/header/MenuBar.spec.tsx
  apps/1CD/instagram/frontend/specs/components/header/UserBar.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/layout.tsx
  apps/1CD/instagram/frontend/src/app/(main)/page.tsx
  apps/1CD/instagram/frontend/src/app/page.tsx
  apps/1CD/instagram/frontend/src/components/SuggestUser.tsx
  apps/1CD/instagram/frontend/src/components/header/Header.tsx
  apps/1CD/instagram/frontend/src/components/header/MenuBar.tsx
  apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
Labels: PR status: code ready, frontend, instagram

#427 418 tinderlst of otp frontend page
  apps/1CD/tinder/frontend/cypress/e2e/(public)/register/email/register-email.cy.tsx
  apps/1CD/tinder/frontend/cypress/e2e/(public)/register/otp/verify-otp.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/project.json
  apps/1CD/tinder/frontend/src/app/(public)/register/email/page.tsx
  apps/1CD/tinder/frontend/src/app/(public)/register/otp/page.tsx
Labels: PR status: code ready

#328 feat(header&footer): concert-frontend
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(admin)/home-page.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/sign-up/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/validationschema.ts
  apps/1CD/concert-ticket-booking/frontend/public/images/logo.png
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignIn.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignUp.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/Footer.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/header.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/(user)/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/(user)/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/(user)/sign-in/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/(user)/sign-up/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/Header.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignIn.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignUp.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/auth/SignUp.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/footer/Footer.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/index.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#432 feat: forget and reset apssword
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/forget-password.cy.tsx
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/resetpassword.cy.tsx
  apps/1CD/instagram/frontend/cypress/utils/all-pages.json
  apps/1CD/instagram/frontend/public/images/lock.png
  apps/1CD/instagram/frontend/src/app/(auth)/forget-password/page.tsx
  apps/1CD/instagram/frontend/src/app/(auth)/resetpassword/page.tsx
  apps/1CD/instagram/frontend/src/app/layout.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#437 feat(hotel-booking-frontend-roomcard): roomCard done
  apps/1CD/hotel-booking/frontend/specs/components/Room-Card.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/RoomCard.tsx
Labels: PR status: code ready

#407 Employee Table connected to Back-End
  apps/1CD/leave-request/frontend/cypress/e2e/admin/table-static.cy.tsx
  apps/1CD/leave-request/frontend/next.config.js
  apps/1CD/leave-request/frontend/project.json
  apps/1CD/leave-request/frontend/src/app/(public)/sendOtp/SendOtp.tsx
  apps/1CD/leave-request/frontend/src/components/admin/EmployeeList.tsx
  apps/1CD/leave-request/frontend/src/components/admin/TableStatic.tsx
  apps/1CD/leave-request/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#436 feat: added pass's cypress but needed some improvement
  apps/1CD/tinder/frontend/cypress/e2e/(public)/register/password/create-pass.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(public)/register/email/page.tsx
  apps/1CD/tinder/frontend/src/app/(public)/register/otp/page.tsx
  apps/1CD/tinder/frontend/src/app/(public)/register/password/page.tsx
  apps/1CD/tinder/frontend/src/app/layout.tsx
  apps/1CD/tinder/frontend/src/graphql/user/register.graphql
Labels: PR status: code ready

#439 connect in userId in post
  apps/1CD/instagram/frontend/next.config.js
  apps/1CD/instagram/frontend/public/images/profileImg.webp
  apps/1CD/instagram/frontend/specs/components/post/PostCard.spec.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/components/providers/ApolloWrapper.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#268 12 tinder birthday input
  apps/1CD/tinder/frontend/cypress/e2e/(main)/birthday.cy.tsx
  apps/1CD/tinder/frontend/cypress/e2e/(public)/register/email/register-email.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/public/img/images.jpeg
  apps/1CD/tinder/frontend/public/img/logo.svg
  apps/1CD/tinder/frontend/src/app/(main)/register/birthday/page.tsx
Labels: PR status: code ready

#451 get following user data
  apps/1CD/instagram/backend/specs/resolvers/queries/follow/see-followings-query.spec.ts
  apps/1CD/instagram/backend/src/models/follow.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/follow/see-followings-query.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
Labels: PR status: code ready

#450 feat(concert-backend): populate added
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/event/get-events.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready

#455 feat: tinder:fixed token
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/verify-otp-flow.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/create-token-cookie.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/create-password.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/verify-otp.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/utils/user/create-token-cookie.ts
Labels: PR status: code ready

#453 edit post model
  apps/1CD/instagram/backend/src/models/post.model.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#460 fixed login error
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/login.cy.tsx
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/signup.cy.tsx
  apps/1CD/instagram/frontend/cypress/utils/all-pages.json
  apps/1CD/instagram/frontend/src/app/(auth)/login/page.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/instagram/frontend/src/components/providers/index.ts
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#465 get followers query
  apps/1CD/instagram/backend/specs/resolvers/queries/follow/see-followers-query.spec.ts
  apps/1CD/instagram/backend/src/models/follow.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/follow/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/follow/see-followers-query.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
Labels: PR status: code ready, backend

#468 feat(hotel-booking-backend): filter by starRating
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#470 feat(hotel-booking-backend): filter by userrating
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#472 feat(hotel-booking-backedn): filter by hotel amenities
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#473 logout button
  apps/1CD/instagram/frontend/specs/components/header/UserBar.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/page.tsx
  apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready, frontend

#446 feat: tinder image upload front
  apps/1CD/tinder/frontend/cypress/e2e/(main)/image.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/sign-up/image/page.tsx
  apps/1CD/tinder/frontend/src/graphql/user/register.graphql
Labels: PR status: code ready

#476 feat(concert-frontend): dayjs added
  package.json
  yarn.lock
Labels: PR status: code ready

#475 279 leave req my request page
  apps/1CD/leave-request/frontend/cypress.config.ts
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/date-picker.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/my-request.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/requests.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/home-page.cy.tsx
  apps/1CD/leave-request/frontend/cypress/fixtures/example.json
  apps/1CD/leave-request/frontend/cypress/support/commands.js
  apps/1CD/leave-request/frontend/cypress/support/component-index.html
  apps/1CD/leave-request/frontend/cypress/support/component.js
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(public)/login/Login.tsx
  apps/1CD/leave-request/frontend/src/app/(user)/MyRequest/page.tsx
  apps/1CD/leave-request/frontend/src/app/layout.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/Requests.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/SentRequest.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/UserHeader.tsx
Labels: PR status: code ready

#477 feat(hotel-booking): admin home page cypress
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/admin/homePage.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/page.tsx
Labels: PR status: code ready

#442 feat: tinder image upload, all-set front
  apps/1CD/tinder/frontend/cypress/e2e/(main)/all-set.cy.tsx
  apps/1CD/tinder/frontend/cypress/e2e/(main)/image.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/sign-up/all-set/page.tsx
  apps/1CD/tinder/frontend/src/app/(main)/sign-up/image/page.tsx
Labels: PR status: code ready

#486 feat: fixed mutation of attraction
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/update-attraction.spec.ts
  apps/1CD/tinder/backend/src/models/user/user.model.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/update-attraction.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#481 edit query getmypost
  apps/1CD/instagram/backend/specs/resolvers/queries/post/get-my-post.spec.ts
  apps/1CD/instagram/backend/src/models/post.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-my-posts.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#483 feat(hotel-booking): hotel-booking frontend
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/.gitkeep
  apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
Labels: PR status: code ready

#487 feat: added cookie in front
  apps/1CD/tinder/frontend/cypress/e2e/(main)/register/birthday.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/register/birthday/page.tsx
  apps/1CD/tinder/frontend/src/app/(public)/register/otp/page.tsx
  apps/1CD/tinder/frontend/src/app/(public)/register/password/page.tsx
  apps/1CD/tinder/frontend/src/app/layout.tsx
  apps/1CD/tinder/frontend/src/app/token/route.ts
  apps/1CD/tinder/frontend/src/components/providers/ApolloWrapper.tsx
  apps/1CD/tinder/frontend/src/components/register/CreatePassword.tsx
  apps/1CD/tinder/frontend/src/graphql/user/register.graphql
Labels: PR status: code ready

#492 confirm follow request mutation
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/confirm-follow-req.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/confirm-follow-req.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
  apps/1CD/instagram/backend/src/types/index.d.ts
Labels: PR status: code ready, backend

#493 edit getmypost in graphql
  apps/1CD/instagram/frontend/specs/components/post/PostCard.spec.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#494 feat(hotel-booking-frontend): add rooms frontned
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/add-hotel/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/specs/components/SelectRoomTypes.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/StarsStaticJson.spec.ts
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/AddHotelGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/AddRoomGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/components/SelectRoomTypes.tsx
  apps/1CD/hotel-booking/frontend/src/components/StarsStaticJson.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#502 499 [hotel booking backend] get rooms one change
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
Labels: PR status: code ready

#503 feat(concert-ticket-loading): signin&signup loading
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/sign-in/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/sign-up/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignIn.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignUp.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/header.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/loading/Loading.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/(user)/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/sign-in/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/sign-up/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignIn.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignUp.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/footer/Footer.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/loading/Loading.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready

#501 416 leave req supervisor front v1
  apps/1CD/leave-request/frontend/public/Avatar.png
  apps/1CD/leave-request/frontend/src/app/supervisor/page.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/DateRangeButton.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/Header.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestApproveButton.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestDenyButton.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestDetail.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestHeader.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestList.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/Requests.tsx
Labels: PR status: code ready

#509 frontend-notification-component
  apps/1CD/instagram/frontend/specs/components/notification/index.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/layout.tsx
  apps/1CD/instagram/frontend/src/app/(main)/page.tsx
  apps/1CD/instagram/frontend/src/components/notification/index.tsx
  apps/1CD/instagram/frontend/src/components/providers/UserProvider.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#464 feat(concert-frontend): homepage
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/home/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/next.config.js
  apps/1CD/concert-ticket-booking/frontend/specs/components/Card.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/Card.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#513 feat(hotel-booking-backend): getrooms filter change
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-rooms.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
Labels: PR status: code ready

#512 edit env connection
  apps/1CD/leave-request/frontend/src/components/providers/ApolloWrapper.tsx
Labels: PR status: code ready

#480 296 leave request form
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-available-paid-request.spec.ts
  apps/1CD/leave-request/backend/src/models/request.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/request/create-request.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-available-requests.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
  apps/1CD/leave-request/backend/src/utils/calc-total-hours.ts
  apps/1CD/leave-request/backend/src/utils/create-token.ts
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/CreateNewRequest.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/SelectRequestType.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/SelectType.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/generate-hourst.ts
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/page.tsx
  apps/1CD/leave-request/frontend/src/app/page.tsx
  apps/1CD/leave-request/frontend/src/components/static/FileUpload.tsx
  apps/1CD/leave-request/frontend/src/components/ui/ComboBox.tsx
  apps/1CD/leave-request/frontend/src/components/ui/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/graphql/createRequest.graphql
  apps/1CD/leave-request/frontend/src/utils/get-email.ts
  apps/1CD/leave-request/frontend/src/utils/upload-files.ts
Labels: PR status: code ready

#522 feat: [tinder]:fixed context and added sign in
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/birthday.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/check-email.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/create-password.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/register-email-flow.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/resend-otp.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/sign-in.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/update-attraction.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/update-user.spec.ts
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/verify-otp-flow.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/sendOtp.spec.ts
  apps/1CD/tinder/backend/src/handler.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/birthday.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/create-password.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/register-with-email.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/sign-in.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/update-attraction.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/update-user.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/types/index.d.ts
  apps/1CD/tinder/backend/src/utils/token.ts
Labels: PR status: code ready

#525 search users backend
  apps/1CD/instagram/backend/specs/resolvers/queries/user/search-users-query.spec.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/user/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/user/search-users-query.ts
  apps/1CD/instagram/backend/src/schemas/user.schema.ts
Labels: PR status: code ready, backend

#526 [concert] docs: changed secret-manager and next config
  apps/1CD/concert-ticket-booking/backend/next.config.js
Labels: PR status: code ready

#519 430 hotel booking frontend get rooms data
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/HomePage.cy.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/AmenitiesFilter.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/DatePicker.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/SearchedHotelCards.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/StarRating.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/search-results/UserRating.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/app/search-result/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/DatePicker.tsx
  apps/1CD/hotel-booking/frontend/src/components/Header.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/AmenitiesCheckbox.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/HeaderFilter.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/RatingRadio.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/SearchedHotelCards.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/StarRating.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#527 get my followings post
  apps/1CD/instagram/backend/specs/resolvers/queries/follow/see-followers-query.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/follow/see-followings-query.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/post/get-my-followings-posts.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/post/get-my-post.spec.ts
  apps/1CD/instagram/backend/src/models/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-my-followings-posts.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-my-posts.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/index.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#529 bug ig
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend

#538 concert:backend:536 concert update event mutation
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/verify-otp.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/create-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/user/get-me.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/models/event.model.ts
  apps/1CD/concert-ticket-booking/backend/src/models/ticket.model.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/create-event.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/user/get-me.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/user/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/auth.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/utils/generate-date.ts
Labels: PR status: code ready, backend

#542 feat(concert-backend): fix populate field
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events.ts
Labels: PR status: code ready, backend

#540 fix(backend): send email
  apps/1CD/instagram/backend/src/utils/sendmail.ts
Labels: PR status: code ready, backend, instagram

#544 543 holboos
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/login.cy.tsx
  apps/1CD/instagram/frontend/cypress/e2e/(auth)/signup.cy.tsx
  apps/1CD/instagram/frontend/src/app/(auth)/forget-password/page.tsx
  apps/1CD/instagram/frontend/src/app/(login)/page.tsx
  apps/1CD/instagram/frontend/src/app/home/layout.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready, frontend, instagram

#551 feat(concert-frontend): card zasav
  apps/1CD/concert-ticket-booking/frontend/src/components/Card.tsx
Labels: PR status: code ready

#552 feat: tinder:fixed token
  apps/1CD/tinder/backend/src/handler.ts
  apps/1CD/tinder/backend/src/utils/token.ts
Labels: PR status: code ready

#550 fix(concert-frontend): test
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/header.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready

#534 feat(hotel-booking-backend): get one booking
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-booking.spec.ts
  apps/1CD/hotel-booking/backend/src/models/booking.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-booking.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#559 backend request update
  apps/1CD/leave-request/backend/src/models/request.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/request/create-request.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-available-requests.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
  apps/1CD/leave-request/backend/src/utils/calc-total-hours.ts
Labels: PR status: code ready

#537 create post in frontend
  apps/1CD/instagram/frontend/next.config.js
  apps/1CD/instagram/frontend/public/images/Drag.png
  apps/1CD/instagram/frontend/public/images/Frame.png
  apps/1CD/instagram/frontend/specs/components/header/MenuBar.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/CreatePost.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/UpdateImagesStep1.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/UpdateImagesStep2.spec.tsx
  apps/1CD/instagram/frontend/src/components/header/MenuBar.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep1.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep2.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#557 makes request
  apps/1CD/leave-request/backend/src/utils/calc-total-hours.ts
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/CreateNewRequest.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/SelectType.tsx
  apps/1CD/leave-request/frontend/src/graphql/createRequest.graphql
  apps/1CD/leave-request/frontend/src/utils/upload-files.ts
Labels: PR status: code ready

#568 bug zasaw in front
  apps/1CD/instagram/frontend/next.config.js
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
Labels: PR status: code ready, frontend, instagram

#569 now can return oldOTP
  apps/1CD/leave-request/backend/src/resolvers/mutations/otp/create-otp.ts
Labels: PR status: code ready

#573 edit create post in backend
  apps/1CD/instagram/backend/specs/resolvers/mutations/post/create-post.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post/create-post.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#574 edit mutation create post
  apps/1CD/instagram/frontend/specs/components/post/PostCard.spec.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#577 bug zasaw IG team
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#578 516 search button function
  apps/1CD/concert-ticket-booking/frontend/next.config.js
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/header.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
Labels: PR status: code ready

#583 feat(concert-frontend): link added
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/page.tsx
Labels: PR status: code ready

#586 next config adds env
  apps/1CD/leave-request/backend/next.config.js
Labels: PR status: code ready

#592 feat(hotel-booking-backend): booking graphql schemas changed
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready

#593 feat(concert-backend): populate
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/event/get-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-event.ts
Labels: PR status: code ready

#594 feat(frontend): user profile
  apps/1CD/instagram/frontend/cypress/e2e/(main)/userName.cy.tsx
  apps/1CD/instagram/frontend/cypress/utils/all-pages.json
  apps/1CD/instagram/frontend/public/images/camera.png
  apps/1CD/instagram/frontend/specs/components/user-profile/NoPost.spec.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/components/header/MenuBar.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/NoPost.tsx
Labels: PR status: code ready, frontend, instagram

#597 504 user cancel booking
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/cancel-booking/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(client)/cancel-booking/page.tsx
Labels: PR status: code ready

#601 change icon
  apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
Labels: PR status: code ready, frontend, instagram

#598 447 hotel booking frontend hoteldetail
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/HotelDetail.cy.tsx
  apps/1CD/hotel-booking/frontend/specs/components/Hotel-Important.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/Hotel-Policies.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/.gitkeep
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/HotelDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/HotelRooms.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/HotelImportant.tsx
  apps/1CD/hotel-booking/frontend/src/components/HotelPolicies.tsx
  apps/1CD/hotel-booking/frontend/src/components/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#560 feat: tinder cloudinary
  apps/1CD/tinder/backend/specs/resolvers/mutations/cloudinary.spec.ts
  apps/1CD/tinder/backend/src/utils/user/cloudinary.ts
Labels: PR status: code ready

#600 531 search users frontend
  apps/1CD/instagram/frontend/cypress/e2e/(main)/SearchComponent.cy.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/SearchComponent.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/components/providers/UserProvider.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#608 feat(hotel-booking-frontend): booking-detail
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/booking-detail/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookiingDetailLeftSideTop.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailCheckInDialog.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailLeftSide.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailLeftSideTop.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailRightSide.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailViewPriceDialog.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/booking-detail/BookingDetailViewRulesDialog.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/booking-detail/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailCheckInDialog.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailLeftSide.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailLeftSideBottom.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailLeftSideMid.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailLeftSideTop.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailRightSide.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailViewPriceDetail.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailViewRulesDialog.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/HeaderFilter.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#609 feat(signin&signup): non header&footer
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignIn.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SignUp.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready, frontend

#610 feat: added hof
  apps/1CD/tinder/backend/src/handler.ts
  apps/1CD/tinder/backend/src/resolvers/index.ts
  apps/1CD/tinder/backend/src/utils/auth.ts
  apps/1CD/tinder/backend/src/utils/token.ts
Labels: PR status: code ready

#622 feat(tinder:installed motion): j
  package.json
  yarn.lock
Labels: PR status: code ready

#626 feat(hotel-booking-backend): room schema changed
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#628 feat(hotel-booking-backend): hb-backend getbookings with jest test
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-booking-find-by-user-id.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-user-find-by-id.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready

#632 feat(concert-frontend): get related events with current event
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/event/get-related-events.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-related-events.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready, backend

#631 348 req change
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/change-order-req.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/change-order-req.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/order.schema.ts
Labels: PR status: code ready, backend

#639 feat(concert-frontend): detail page top component
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/home/event/[eventId]/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/(user)/home/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/DetailTop.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/DetailTop.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#642 feat((hotel-booking-backend)): signup sendotp verifyotp backend ynzalsan
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/user/send-otp.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/user/verify-otp.spec.ts
  apps/1CD/hotel-booking/backend/src/components/check-expiration.ts
  apps/1CD/hotel-booking/backend/src/models/otp.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/user/send-otp.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/user/verify-otp.ts
  apps/1CD/hotel-booking/backend/src/schemas/user.schema.ts
  apps/1CD/hotel-booking/backend/src/utils/generate-otp.ts
Labels: PR status: code ready, backend

#641 607 linking sidebar with components
  apps/1CD/instagram/frontend/cypress/e2e/(main)/Header.cy.tsx
  apps/1CD/instagram/frontend/cypress/e2e/(main)/SearchComponent.cy.tsx
  apps/1CD/instagram/frontend/specs/components/header/Header.spec.tsx
  apps/1CD/instagram/frontend/specs/components/header/MenuBar.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/SearchComponent.tsx
  apps/1CD/instagram/frontend/src/app/home/layout.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/app/layout.tsx
  apps/1CD/instagram/frontend/src/components/header/Header.tsx
  apps/1CD/instagram/frontend/src/components/header/MenuBar.tsx
  apps/1CD/instagram/frontend/src/components/providers/UserProvider.tsx
Labels: PR status: code ready, frontend

#615 feat(fe): project json
  apps/1CD/instagram/frontend/project.json
Labels: PR status: code ready, frontend, instagram

#646 create post like mutation
  apps/1CD/instagram/backend/specs/resolvers/mutations/post-like/create-post-like.spec.ts
  apps/1CD/instagram/backend/src/models/index.ts
  apps/1CD/instagram/backend/src/models/post-like.model.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post-like/create-post-like.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post-like/index.ts
  apps/1CD/instagram/backend/src/schemas/index.ts
  apps/1CD/instagram/backend/src/schemas/post-like.schema.ts
Labels: PR status: code ready, backend, instagram

#635 feat: tinder birthday input change
  apps/1CD/tinder/frontend/cypress/e2e/(main)/register/birthday.cy.tsx
  apps/1CD/tinder/frontend/src/app/(main)/register/birthday/page.tsx
Labels: PR status: code ready

#618 Create employee without test
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/components/admin/CreateEmployeeModal.tsx
  apps/1CD/leave-request/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#654 get post likes query
  apps/1CD/instagram/backend/specs/resolvers/queries/post-like/get-post-likes.spec.ts
  apps/1CD/instagram/backend/src/models/post-like.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post-like/get-post-likes.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post-like/index.ts
  apps/1CD/instagram/backend/src/schemas/post-like.schema.ts
Labels: PR status: code ready, backend, instagram

#655 feat: tinder image upload backend
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/image.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/image.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#640 feat: bookings query
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-bookings.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/hotel/get-hotels.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-bookings.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready, backend

#659 656 hotel booking backend schema change requirement
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#658 650 get post backend
  apps/1CD/instagram/backend/specs/resolvers/queries/post/get-post.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/comment/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-post.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/index.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#663 feat(concert-backend): delete last event
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/delete-last-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/delete-last-event.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/update-event-priority.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready, backend

#664 feat(hotel-booking-backend): verify-otp-zasvar-bolon model schema jij…
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/user/verify-otp.spec.ts
  apps/1CD/hotel-booking/backend/src/models/user.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/user/verify-otp.ts
  apps/1CD/hotel-booking/backend/src/schemas/index.ts
Labels: PR status: code ready, backend

#667 fix(concert-frontend): delete image from cloudinary
  apps/1CD/concert-ticket-booking/frontend/cypress.config.ts
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/EventModal.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputImage.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/fixtures/mock-image.png
  apps/1CD/concert-ticket-booking/frontend/next.config.js
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/EvenModal.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/GenreWithLocation.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/InputArtist.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/InputImage.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/TicketInputs.tsx
  apps/1CD/concert-ticket-booking/frontend/src/utils/generate-signature.ts
Labels: PR status: code ready, backend

#668 643 remove follower backend
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/remove-follower.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/remove-follower.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-my-followings-posts.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
Labels: PR status: code ready, backend

#669 unfollow-backend
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/unfollow.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/unfollow.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
Labels: PR status: code ready, backend

#671 get user backend
  apps/1CD/instagram/backend/specs/resolvers/queries/user/get-logged-user-query.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/user/get-one-user-query.spec.ts
  apps/1CD/instagram/backend/src/resolvers/queries/user/get-logged-user-query.ts
  apps/1CD/instagram/backend/src/resolvers/queries/user/get-one-user-query.ts
  apps/1CD/instagram/backend/src/resolvers/queries/user/index.ts
  apps/1CD/instagram/backend/src/schemas/user.schema.ts
Labels: PR status: code ready, backend

#660 612 ig fe user profiliin zurag solih angid
  apps/1CD/instagram/frontend/cypress/e2e/(main)/userName.cy.tsx
  apps/1CD/instagram/frontend/specs/components/user-profile/ChangeProImg.spec.tsx
  apps/1CD/instagram/frontend/specs/components/user-profile/NoPost.spec.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/ChangeProImg.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/NoPost.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#678 perf(concert-backend): change auth response
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/change-password.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/recover-password.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/verify-otp.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/verify-user-email.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/change-password.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/recover-password.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/verify-otp.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/verify-user-email.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/auth.schema.ts
Labels: PR status: code ready, backend

#673 [hotel booking frontend] booking confirm
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/booking-confirm/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/checkout/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/public/images/Frame.png
  apps/1CD/hotel-booking/frontend/specs/components/BookingRightSide.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/booking-confirm/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/checkout/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailLeftSideTop.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingDetailRightSide.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingPageRightSide.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#571 secret manager fix
  apps/1CD/leave-request/frontend/project.json
Labels: PR status: code ready

#625 header is dynamic
  apps/1CD/leave-request/frontend/cypress/e2e/admin/create-employee.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/admin/date-picker.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/admin/table-static.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/render-all.pages.cy.tsx
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(main)/createNewRequest/CreateNewRequest.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/layout.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/leaveCalendar/page.tsx
  apps/1CD/leave-request/frontend/src/components/admin/Header.tsx
  apps/1CD/leave-request/frontend/src/utils/decode-token.ts
Labels: PR status: code ready, frontend

#679 feat(concert-frontend): embla carousel
  package.json
  yarn.lock
Labels: PR status: code ready, frontend

#682 feat(concert-backend): date yo isostring
  apps/1CD/concert-ticket-booking/backend/src/utils/generate-date.ts
Labels: PR status: code ready

#684 feat(concert-frontend): card date update
  apps/1CD/concert-ticket-booking/frontend/specs/components/Card.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/Card.tsx
Labels: PR status: code ready

#688 feat: tinder-attractipon finished
  apps/1CD/tinder/frontend/cypress/e2e/(main)/register/attraction.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/register/attraction/page.tsx
  apps/1CD/tinder/frontend/src/graphql/about/attraction.graphql
Labels: PR status: code ready, frontend

#689 check me query
  apps/1CD/leave-request/backend/specs/resolvers/queries/handyQueries/check-me.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/handyQueries/check-me.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/handyQueries/index.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/index.ts
  apps/1CD/leave-request/backend/src/schemas/index.ts
  apps/1CD/leave-request/backend/src/schemas/util.schema.ts
  apps/1CD/leave-request/backend/src/utils/check-token.ts
Labels: PR status: code ready, backend

#692 feat(concert-frontend): verify user email
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/event/[eventId]/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/sign-in/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/sign-up/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/verify-email/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignIn.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/auth/SignUp.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/utils/ErrorBoundary.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/sign-in/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/sign-up/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/verify-email/_components/VerifyEmail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/verify-email/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/auth/SignIn.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/auth/SignUp.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/all.graphql
  apps/1CD/concert-ticket-booking/frontend/tsconfig.json
Labels: PR status: code ready, frontend

#686 feat(hotel-booking-frontend): signup login frontend done
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/(auth)/login/index.cy.ts
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/(auth)/signup/index.cy.ts
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/(auth)/signup/otp/index.cy.ts
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/(auth)/signup/password/index.cy.ts
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/cypress/utils/intercept-graphql.ts
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/_components/ChangePassword.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/_components/Login.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/_components/SetPassword.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/_components/VerifyEmail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/_components/VerifyOtp.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/change-password/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/login/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/signup/otp/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/signup/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/signup/password/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/hotel-detail/HotelRooms.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/index.ts
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#696 feat: bookings query and unit test
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-bookings.spec.ts
  apps/1CD/hotel-booking/backend/src/models/booking.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-bookings.ts
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready, backend

#695 login signup button darahad userdeg bolson
  apps/1CD/hotel-booking/frontend/specs/components/Header.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/(auth)/change-password/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(client)/layout.tsx
  apps/1CD/hotel-booking/frontend/src/app/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/Header.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready, frontend

#698 feat(concert-frontend): set env nextconfig
  apps/1CD/concert-ticket-booking/backend/next.config.js
Labels: PR status: code ready, backend
