Repository pinecone-studio/pinecone-intern-monorepo-2, pull requests merged in 2025-01, with the labels that each got.

#1005 feat(hotel-booking-frontend): cypress fixed
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/room-card/roomCard.cy.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/checkout/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelRoomDetail.tsx
  apps/1CD/hotel-booking/frontend/src/components/PriceDetail.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/DialogUtil.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/HotelBookingDialog.tsx
Labels: PR status: code ready

#999 995 hotel booking backend filter by properties
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/room/add-room-service.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/rooms/add-room.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/filter-by-properties-hotels.spec.ts
  apps/1CD/hotel-booking/backend/src/components/rooms-price-average.ts
  apps/1CD/hotel-booking/backend/src/models/hotels.model.ts
  apps/1CD/hotel-booking/backend/src/models/rooms.model.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/room/add-room-service.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/rooms/add-room.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/filter-by-properties-hotels.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/filter-types.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-rooms.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
  apps/1CD/hotel-booking/frontend/src/components/DatePicker.tsx
Labels: PR status: code ready

#1011 Role checkbox updated
  apps/1CD/leave-request/frontend/src/components/admin/TableStatic.tsx
  apps/1CD/leave-request/frontend/src/graphql/all.graphql
Labels: PR status: code ready, backend

#1006 style(home pagenii postuudiin urgun uurchlugduj bsaniig boliulsan): h…
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
Labels: PR status: code ready, frontend, instagram

#1016 opens the request
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/open-request.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/index.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/open-request.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready, backend

#1019 open request
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/open-request.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/open-request.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1015 1012 story backend
  apps/1CD/instagram/backend/specs/resolvers/mutations/auth/login.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/mutations/auth/signup.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/mutations/story/create-story.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/story/create-story.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/story/index.ts
  apps/1CD/instagram/backend/src/schemas/index.ts
  apps/1CD/instagram/backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#1025 feat: tinder:match done
  apps/1CD/tinder/backend/specs/resolvers/mutations/swipe/swipe.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/swipe/swipe.ts
  apps/1CD/tinder/backend/src/schemas/swipe/swipe.schema.ts
Labels: PR status: code ready

#1027 feat(hotel-booking-backend): get room query done
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/rooms/get-room.spec.ts
  apps/1CD/hotel-booking/backend/src/components/rooms-price-average.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/get-room.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/rooms/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#1032 adds entity for createdAt
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#978 791 guests info page
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/room-card/roomCard.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/guests/guest-info/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/DataTable.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/GuestCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/guests-info/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/page.tsx
Labels: PR status: code ready

#1040 feat: tinder:done backend get user
  apps/1CD/tinder/backend/specs/resolvers/mutations/swipe/match.spec.ts
  apps/1CD/tinder/backend/src/resolvers/queries/swipe/index.ts
  apps/1CD/tinder/backend/src/resolvers/queries/swipe/match.ts
  apps/1CD/tinder/backend/src/schemas/swipe/swipe.schema.ts
Labels: PR status: code ready

#1038 1008 ig be notifications
  apps/1CD/instagram/backend/specs/resolvers/queries/notification/get-notifications.spec.ts
  apps/1CD/instagram/backend/src/models/index.ts
  apps/1CD/instagram/backend/src/models/notifications.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/notifications/get-notifications.ts
  apps/1CD/instagram/backend/src/resolvers/queries/notifications/index.ts
  apps/1CD/instagram/backend/src/schemas/index.ts
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1044 993 buy ticket
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/DateWithRange.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/EventModal.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputArtists.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputGenreWithLocation.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/TimePicker.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/filter/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/order/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/orders-mock.ts
  apps/1CD/concert-ticket-booking/frontend/public/images/qpay.png
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/EvenModal.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/InputImage.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/DatePicker.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/EventDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/TicketDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/[id]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderConfirm.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/Payment.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/ticket.graphql
  apps/1CD/concert-ticket-booking/frontend/src/utils/type.ts
Labels: PR status: code ready, frontend

#1046 feat(filter page): filter page done
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/filter/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/filter/page.tsx
Labels: PR status: code ready, frontend

#1041 guest-info
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/DataTable.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/GuestCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/guests-info/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/search-hotel/SearchedHotelCards.tsx
Labels: PR status: code ready

#1050 likes modal done
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostLikes.tsx
  apps/1CD/instagram/frontend/src/graphql/PostLike.graphql
Labels: PR status: code ready, frontend, instagram

#1039 741 leave request supervisor frontend connection
  apps/1CD/leave-request/frontend/src/app/(main)/supervisor/page.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestApproveButton.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestDenyButton.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestDetail.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestHeader.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestList.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/Requests.tsx
  apps/1CD/leave-request/frontend/src/context/GetAllRequestBySupervisorContext.tsx
  apps/1CD/leave-request/frontend/src/graphql/open-request.graphql
  apps/1CD/leave-request/frontend/src/graphql/supervisor.graphql
Labels: PR status: code ready

#1030 feat(concert-frontend): skeleton
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/filter/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/SkeletonCarausel.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/SkeletonCard.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/global.css
  apps/1CD/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/DatePicker.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/_components/index.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/filter/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/Card.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SkeletonCarausel.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/SkeletonCard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
  apps/1CD/concert-ticket-booking/frontend/src/utils/show-tugrik-format.ts
  libs/shadcn/src/lib/ui/dialog.tsx
Labels: PR status: code ready

#1055 feat(concert-frontend): fix
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/ticket/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/filter/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/[id]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderConfirm.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/Payment.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/ticket/[unitId]/page.tsx
Labels: PR status: code ready, frontend

#1059 create story frontend
  apps/1CD/instagram/frontend/specs/components/story/CreateStory.spec.tsx
  apps/1CD/instagram/frontend/specs/components/story/DiscardStory.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/HeadingSection.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/components/story/CreateStory.tsx
  apps/1CD/instagram/frontend/src/components/story/DiscardStory.tsx
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready

#1052 Employee Table
  apps/1CD/leave-request/frontend/cypress/e2e/admin/table-static.cy.tsx
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(main)/admin/page.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/employeeList/page.tsx
  apps/1CD/leave-request/frontend/src/components/admin/EmployeeTable.tsx
  apps/1CD/leave-request/frontend/src/components/admin/TableStatic.tsx
  apps/1CD/leave-request/frontend/src/components/admin/TableStaticDataless.tsx
  apps/1CD/leave-request/frontend/src/components/layout-components/Header.tsx
Labels: PR status: code ready, frontend

#1073 feat: tinder:fixed smth
  apps/1CD/tinder/frontend/cypress/e2e/(main)/home/home-page.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/home/.gitignore
  apps/1CD/tinder/frontend/src/app/(main)/home/page.tsx
Labels: PR status: code ready

#1078 feat(be): ehnii eeljind createpostLike dotor like darahad davhar noti…
  apps/1CD/instagram/backend/specs/resolvers/mutations/post-like/create-post-like.spec.ts
  apps/1CD/instagram/backend/src/models/notifications.model.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post-like/create-post-like.ts
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1079 story backend queries
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-following-stories.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-stories.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-story.spec.ts
  apps/1CD/instagram/backend/src/models/story.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-following-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-story.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/index.ts
  apps/1CD/instagram/backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#1072 feat(concert-frontend): populate
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/event/get-events.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events.ts
Labels: PR status: code ready

#1043 feat: adminTable updatePriority button
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/UpdateEventPriority.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/home-page.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/UpdateEventPriority.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#1082 feat(concert-frontend): cache bug fix
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/orders-mock.ts
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/order.graphql
Labels: PR status: code ready, frontend

#1084 feat(tinder): fixed update user on profile
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/profile-edit.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/profile-edit.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#1085 fix(be): get notification
  apps/1CD/instagram/backend/specs/resolvers/queries/notification/get-notifications.spec.ts
  apps/1CD/instagram/backend/src/models/notifications.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/notifications/get-notifications.ts
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1086 1077 tinderfixed mutation protection
  apps/1CD/tinder/backend/src/resolvers/index.ts
Labels: PR status: code ready

#1088 comment
  apps/1CD/instagram/frontend/specs/components/SuggestUser.spec.tsx
  apps/1CD/instagram/frontend/specs/components/comment/CommentCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/comment/LastCommentCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostWithComments.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/components/SuggestUser.tsx
  apps/1CD/instagram/frontend/src/components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/components/comment/LastCommentCard.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/graphql/PostComment.graphql
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready, frontend, instagram

#1090 get post by postId in backend
  apps/1CD/instagram/backend/specs/resolvers/queries/post/get-post-by-postId.spec.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-post-by-post-id.ts
  apps/1CD/instagram/backend/src/resolvers/queries/post/index.ts
  apps/1CD/instagram/backend/src/schemas/post.schema.ts
Labels: PR status: code ready, backend, instagram

#1093 perf(concert-frontend): improve table data
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/page.tsx
Labels: PR status: code ready, frontend

#1095 fix(be): notification model-objectId tai bolgoh
  apps/1CD/instagram/backend/src/models/notifications.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/notifications/get-notifications.ts
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1097 feat(concert-backend): get requests
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/request/get-requests.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/get-venue.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/request/get-requests.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/request/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/request.schema.ts
  apps/1CD/concert-ticket-booking/backend/src/utils/generate-token.ts
Labels: PR status: code ready, backend

#1100 fix(be): notificationii yag final zasvar
  apps/1CD/instagram/backend/src/models/notifications.model.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/notifications/get-notifications.ts
Labels: PR status: code ready, backend, instagram

#1102 fix(be): notification doh postmodel iig post bolgoson
  apps/1CD/instagram/backend/src/models/notifications.model.ts
Labels: PR status: code ready, backend, instagram

#1109 fix(concert-backend): add populate in query
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/request/get-requests.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/request/get-requests.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/request.schema.ts
Labels: PR status: code ready, backend

#1111 feat(concert-frontend): cancel ticket page done
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/cancel-request/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputArtists.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/TicketInputs.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/home-page.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/home/user-profile/OrderInfo.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/orders-mock.ts
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/cancel-request/_components/ModalStatus.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/cancel-request/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminFooter.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminHeader.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/request.graphql
  apps/1CD/concert-ticket-booking/frontend/src/utils/to-check.ts
Labels: PR status: code ready, frontend

#1064 header dynamic
  apps/1CD/leave-request/frontend/cypress.config.ts
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(main)/create-request.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/date-picker.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/my-request.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(user)/myRequest/requests.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/admin/create-employee.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/admin/date-picker.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/admin/table-static.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/render-all.pages.cy.tsx
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(main)/MyRequest/page.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/admin/page.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/supervisor/page.tsx
  apps/1CD/leave-request/frontend/src/app/page.tsx
  apps/1CD/leave-request/frontend/src/components/admin/CreateEmployeeModal.tsx
  apps/1CD/leave-request/frontend/src/components/createNewRequest/SelectType.tsx
  apps/1CD/leave-request/frontend/src/components/layout-components/Header.tsx
  apps/1CD/leave-request/frontend/src/components/layout-components/NavBar.tsx
  apps/1CD/leave-request/frontend/src/components/layout-components/ProfilePic.tsx
  apps/1CD/leave-request/frontend/src/components/login/SendOtp.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/SentRequest.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestDetail.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestList.tsx
  apps/1CD/leave-request/frontend/src/context/GetAllRequestBySupervisorContext.tsx
  apps/1CD/leave-request/frontend/src/context/SecurePageWrapper.tsx
  apps/1CD/leave-request/frontend/src/utils/generate-hourst.ts
Labels: PR status: code ready

#1115 get post with comments
  apps/1CD/instagram/frontend/specs/components/comment/CommentCount.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostWithComments.spec.tsx
  apps/1CD/instagram/frontend/src/components/comment/CommentCount.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#1117 bug in postid query in backend
  apps/1CD/instagram/backend/src/resolvers/queries/post/get-post-by-post-id.ts
Labels: PR status: code ready, backend, instagram

#1119 add like mutatution in postwithComments modal
  apps/1CD/instagram/frontend/specs/components/like/PostLike.spec.tsx
  apps/1CD/instagram/frontend/specs/components/like/PostLikes.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostWithComments.spec.tsx
  apps/1CD/instagram/frontend/src/components/like/PostLike.tsx
  apps/1CD/instagram/frontend/src/components/like/PostLikes.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
Labels: PR status: code ready, frontend, instagram

#1124 docs(be): notification schema nemsen
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1127 feat(concert-backend): add payment check
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/add-to-cart.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/payment-check.spec.ts
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/order/payment-ticket.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/models/order.model.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/add-to-cart.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/payment-check.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/order/payment-ticket.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/order.schema.ts
Labels: PR status: code ready, backend

#1128 update post
  apps/1CD/instagram/frontend/specs/components/post/UpdatePost.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/HeadingSection.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard.spec.tsx
  apps/1CD/instagram/frontend/src/app/(auth)/forget-password/page.tsx
  apps/1CD/instagram/frontend/src/app/(auth)/resetpassword/page.tsx
  apps/1CD/instagram/frontend/src/app/(auth)/signup/page.tsx
  apps/1CD/instagram/frontend/src/app/(login)/page.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/SearchComponent.tsx
  apps/1CD/instagram/frontend/src/components/like/PostLikes.tsx
  apps/1CD/instagram/frontend/src/components/notification/index.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep1.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep2.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdatePost.tsx
  apps/1CD/instagram/frontend/src/components/story/CreateStory.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/ChangeProImg.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowerDialog.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowingDialog.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/NoPost.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/HeadingSection.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostsSection.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowers.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowings.tsx
  apps/1CD/instagram/frontend/src/graphql/Post.graphql
Labels: PR status: code ready, frontend, instagram

#1129 1110 story backend edit schema
  apps/1CD/instagram/backend/specs/resolvers/mutations/story-view/create-view-story-mutation.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/mutations/story/create-story.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story-view/get-story-view-query.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-story.spec.ts
  apps/1CD/instagram/backend/src/models/index.ts
  apps/1CD/instagram/backend/src/models/story-view.model.ts
  apps/1CD/instagram/backend/src/models/story.model.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/view-story/ create-view-story-mutation.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/view-story/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story-view/get-story-view-query.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story-view/index.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-following-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-story.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-public-acc-stories.ts
  apps/1CD/instagram/backend/src/schemas/index.ts
  apps/1CD/instagram/backend/src/schemas/story.schema.ts
  apps/1CD/instagram/backend/src/schemas/view-story.schema.ts
Labels: PR status: code ready

#1131 delete post
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard2.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/DropMenu.tsx
  apps/1CD/instagram/frontend/src/components/post/DeleteModal.tsx
  apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdatePost.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready, frontend, instagram

#1130 feat(concert-frontend): add payment page
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/order/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/payment/[id]/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/next.config.js
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/[id]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderConfirm.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/Payment.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/payment/[id]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/ticket/[unitId]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/all.graphql
  apps/1CD/concert-ticket-booking/frontend/src/graphql/ticket.graphql
Labels: PR status: code ready, frontend

#1135 feat(concert-frontend): user profile
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/PasswordReset.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/UserInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/page.tsx
Labels: frontend

#1136 edit modal
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostsSection.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/DropMenu.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdatePost.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostImgCard.tsx
Labels: PR status: code ready, frontend, instagram

#1133 feat(hotel-booking-backend): add hotelId filter in getBookings query …
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/booking/udpate-booking-status.spec.ts
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-bookings.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/booking/update-bookin-status.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-bookings.ts
  apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready

#1107 feat(hotel-booking-backend): get user query done
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/users/get-user.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/users/get-user.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/users/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/user.schema.ts
Labels: PR status: code ready

#1139 edit mutation delete and update post
  apps/1CD/instagram/backend/specs/resolvers/mutations/post/delete-post.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/mutations/post/update-post.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post/delete-post.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/post/update-post.ts
Labels: PR status: code ready, backend, instagram

#1141 1083 header responsive
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
Labels: PR status: code ready, frontend

#1140 feat(hotel-image-detail): image detail done
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/room-card/roomCard.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/HotelDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/HotelRooms.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelDetailImage.tsx
Labels: PR status: code ready, frontend

#1145 1142 form validation cancel request
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/Dialog.tsx
Labels: PR status: code ready

#1147 feat(detail page responsive): detail page responsive done
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/EventDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/TicketDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/page.tsx
Labels: PR status: code ready, frontend

#1154 feat(concert-backend): delete event
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/delete-event.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/models/event.model.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/delete-event.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready

#1155 feat(main page): carousel responsive done
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/_components/index.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/Card.tsx
Labels: PR status: code ready, frontend

#1148 891 hotel booking front admin home deer image
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/admin/homePage.cy.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/layout.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/Sidebar.tsx
Labels: PR status: code ready

#1149 feat(hotel-detail button hover style jigdlew): all button style change
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelRoomDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelRooms.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/PriceDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/HomePageCard.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/HeaderFilter.tsx
Labels: PR status: code ready, frontend

#1163 edit carousel
  apps/1CD/instagram/frontend/specs/components/post/Post
  apps/1CD/instagram/frontend/specs/components/post/PostCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostCard.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostImg.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostWithComments.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostCard.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/components/post/PostImg.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
Labels: PR status: code ready, frontend, instagram

#1164 edited story backend
  apps/1CD/instagram/backend/specs/resolvers/mutations/story/create-story.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-following-stories.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-active-story.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-all-stories.spec.ts
  apps/1CD/instagram/backend/specs/resolvers/queries/story/get-my-story.spec.ts
  apps/1CD/instagram/backend/src/models/story.model.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/story/create-story.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-following-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-active-story.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-all-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-stories.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/get-my-story.ts
  apps/1CD/instagram/backend/src/resolvers/queries/story/index.ts
  apps/1CD/instagram/backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#1157 length filter
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-all-request-length.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-reqeust-length.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1171 edit modal
  apps/1CD/instagram/frontend/specs/components/post/Post.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostImgCarousel.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/PostWithComments.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/UpdatePost.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/UpdatePost.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard2.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCard2.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/PostImgCarousel.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/UpdatePost.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/components/post/PostImgCarousel.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostImgCarousel.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostsSection.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready, frontend, instagram

#1150 cant make request of past
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(main)/create-request.cy.tsx
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(public)/login-page.cy.tsx
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/components/login/SendOtp.tsx
  apps/1CD/leave-request/frontend/src/components/ui/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/graphql/supervisor.graphql
Labels: PR status: code ready

#1177 fix: profile Pic fixed
  apps/1CD/leave-request/frontend/src/components/layout-components/ProfilePic.tsx
Labels: PR status: code ready, frontend

#1169 1160 event delete frontend
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/cancel-request/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#1172 feat(hotel-booking-backend): getHotels filter by properties
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/hotel/get-hotels.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/hotels/get-hotels.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
Labels: PR status: code ready

#1181 connect profile page
  apps/1CD/instagram/frontend/specs/components/post/PostImgCarousel.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/components/like/PostLikes.tsx
Labels: PR status: code ready, frontend, instagram

#1184 request length but grouped
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-request-length-with-group.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-reqeust-length.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1187 group the filter
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
  apps/1CD/leave-request/frontend/src/graphql/supervisor.graphql
Labels: PR status: code ready

#1190 feat(trash clean): ttrash clean
  apps/1CD/concert-ticket-booking/backend/src/app/api/order/route.ts
  apps/1CD/concert-ticket-booking/backend/vercel.json
Labels: backend

#1189 connect profile page in comments user
  apps/1CD/instagram/frontend/specs/components/post/DeleteModal.spec.tsx
  apps/1CD/instagram/frontend/specs/components/user-profile/FollowerDialog.spec.tsx
  apps/1CD/instagram/frontend/specs/components/user-profile/FollowingDialog.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/SeeFollowers.spec.tsx
  apps/1CD/instagram/frontend/specs/components/visit-profile/SeeFollowings.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/components/comment/LastCommentCard.tsx
  apps/1CD/instagram/frontend/src/components/post/DeleteModal.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowerDialog.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowingDialog.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowers.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowings.tsx
Labels: PR status: code ready, frontend, instagram

#1179 feat(tinder): added like dislike pics
  apps/1CD/tinder/frontend/cypress/e2e/(main)/swipe/swipe.cy.tsx
  apps/1CD/tinder/frontend/public/like.png
  apps/1CD/tinder/frontend/public/no.svg
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiping.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/like/Dislike.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/like/Like.tsx
Labels: PR status: code ready

#1194 wil await for email to arrive
  apps/1CD/leave-request/backend/src/resolvers/mutations/otp/create-otp.ts
Labels: PR status: code ready

#1196 tinder fix carousel
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiping.tsx
Labels: PR status: code ready

#1197 1121 [hotel booking frontend] admin hotel detail
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/add-hotel/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/admin-hotel-detail/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/guests/guest-info/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/specs/components/BookingStatusBadge.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/admin-hotel-detail/RightSide.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/admin-hotel-detail/RoomTypes.spec.tsx
  apps/1CD/hotel-booking/frontend/specs/components/admin-hotel-detail/UpcomingBookings.spec.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/AddHotelGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/AddRoomGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/admin-hotel-detail/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/ConfirmCheckoutDialog.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/DataTable.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/GuestCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/_components/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/info/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/guests/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/booking/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelAsked.tsx
  apps/1CD/hotel-booking/frontend/src/components/BookingStatusBadge.tsx
  apps/1CD/hotel-booking/frontend/src/components/admin-hotel-detail/RightSide.tsx
  apps/1CD/hotel-booking/frontend/src/components/admin-hotel-detail/RoomTypes.tsx
  apps/1CD/hotel-booking/frontend/src/components/admin-hotel-detail/UpcomingBookings.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/Sidebar.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#1203 feat: tinder
  apps/1CD/tinder/backend/src/schemas/swipe/swipe.schema.ts
Labels: PR status: code ready

#1065 823 tinder sidebar clickandswap
  apps/1CD/tinder/frontend/cypress/e2e/(public)/profile/profile-swap.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/GenderSelect.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/InterstSelect.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/ProfileHeader.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/TabNavigation.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/page.tsx
  apps/1CD/tinder/frontend/src/app/(main)/register/all-set/page.tsx
Labels: PR status: code ready

#1206 create comment
  apps/1CD/instagram/frontend/specs/components/comment/CreateComment.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/components/comment/CreateComment.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/graphql/PostComment.graphql
Labels: PR status: code ready, frontend, instagram

#1207 feat(admin page): admin header desing done
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/cancel-request/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/DateWithRange.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/EventModal.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputArtists.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputGenreWithLocation.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputImage.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/TicketInputs.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/UpdateEventPriority.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/home-page.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/AdminFooter.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/AdminHeader.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/cancel-request/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminHeader.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/1CD/concert-ticket-booking/frontend/src/components/header/Header.tsx
Labels: PR status: code ready, frontend

#1200 1137 ig fe notify postlike
  apps/1CD/instagram/frontend/cypress/e2e/(main)/Header.cy.tsx
  apps/1CD/instagram/frontend/specs/components/notification/index.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/NoNotification.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyFollowReqCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyPostLikeCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostCard.tsx
  apps/1CD/instagram/frontend/src/components/notification/index.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#1211 feat(be): folloew request ilgeehed davhar notification uusne
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/send-follow-req.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/send-follow-req.ts
Labels: PR status: code ready, backend, instagram

#1213 delete comment
  apps/1CD/instagram/frontend/specs/components/comment/CommentCard
  apps/1CD/instagram/frontend/specs/components/comment/CommentCard.spec.tsx
  apps/1CD/instagram/frontend/specs/components/post/DeleteModal.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/DeleteDialog.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/comment/DeleteComment.tsx
  apps/1CD/instagram/frontend/src/components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/components/post/DeleteModal.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/graphql/PostComment.graphql
Labels: PR status: code ready, frontend, instagram

#1220 remove follower
  apps/1CD/instagram/frontend/specs/components/user-profile/FollowerDialog
  apps/1CD/instagram/frontend/specs/components/user-profile/FollowerDialog.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/comment/CommentCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/comment/DeleteComment.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/comment/DeleteDialog.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/follow/FollowerDialog.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/follow/RemoveFollow.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/post/DropMenu.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/post/PostCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/post/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/post/UpdatePost.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowerDialog.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/FollowingDialog.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/HeadingSection.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/PostsSection.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowers.tsx
  apps/1CD/instagram/frontend/src/components/visit-profile/SeeFollowings.tsx
  apps/1CD/instagram/frontend/src/graphql/Follow.graphql
  apps/1CD/instagram/frontend/tsconfig.json
Labels: PR status: code ready, frontend, instagram

#1227 1191 sign out section in tinder
  apps/1CD/tinder/frontend/cypress/e2e/(main)/swipe/swipe.cy.tsx
  apps/1CD/tinder/frontend/cypress/utils/all-pages.json
  apps/1CD/tinder/frontend/public/loading.svg
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Carouselmg.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiper.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiping.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/heaeder/Header.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/page.tsx
  apps/1CD/tinder/frontend/src/app/deleteToken/route.ts
  apps/1CD/tinder/frontend/src/components/Chatsidebar.tsx
  apps/1CD/tinder/frontend/src/components/Matches.tsx
  apps/1CD/tinder/frontend/src/components/Oneuser.tsx
Labels: PR status: code ready

#1226 story page
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/StoryCarouselCard.tsx
  apps/1CD/instagram/frontend/src/app/story/page.tsx
  apps/1CD/instagram/frontend/src/components/story/BigStoryCard.tsx
  apps/1CD/instagram/frontend/src/components/story/CreateStory.tsx
  apps/1CD/instagram/frontend/src/components/story/MainPageStory.tsx
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready

#1229 feat(concert-backend): get order query
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/order/get-order.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/order/get-order.ts
Labels: PR status: code ready, backend

#1235 feat: tidner get me done
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/getMe.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/get-me.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
  apps/1CD/tinder/backend/src/utils/token.ts
Labels: PR status: code ready

#1087 1076 [hotel booking frontend] add room information multiple selection
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/add-hotel/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/booking-confirm/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/booking-detail/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/booking/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/cancel-booking/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/checkout/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/hotel-detail/HotelDetail.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/room-card/roomCard.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(admin)/AddRoomGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(auth)/_components/SetPassword.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/booking-confirm/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/booking-detail/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/booking-detail/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/booking/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/cancel-booking/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/checkout/[id]/page.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/HotelRoomDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/PriceDetail.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/hotel-detail/RoomCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/page.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/AuthProvider.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/CheckLoginUser.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/SignupProvider.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#1238 feat(admin page): admin login desing done
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/cancel-request/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminFooter.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminHeader.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/layout.tsx
Labels: PR status: code ready, frontend

#1225 1199 leave request request length filter
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-all-request-length.spec.ts
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-request-length-with-group.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-reqeust-length.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1242 feat(concert-backend): pagination done
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/queries/event/get-events-pagination.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events-pagination.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/index.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready

#1244 feat: tinder
  apps/1CD/tinder/backend/specs/resolvers/queries/get-me.spec.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/get-me.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/index.ts
  apps/1CD/tinder/backend/src/resolvers/queries/get-me.ts
  apps/1CD/tinder/backend/src/resolvers/queries/index.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
Labels: PR status: code ready

#1245 feat(hotel-booking-frontend): admin page cypress test done
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/admin/homePage.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(admin)/AddHotelGeneralInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/_components/SelectLocation.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/_components/SelectRooms.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/_components/SelectStarRating.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/_components/SelectUserRating.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/page.tsx
  apps/1CD/hotel-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#1251 feat: tinder
  apps/1CD/tinder/backend/src/resolvers/index.ts
Labels: PR status: code ready

#1248 tinder match chat
  apps/1CD/tinder/frontend/src/app/(main)/chat/[id]/page.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiping.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/match/Match.tsx
  apps/1CD/tinder/frontend/src/app/(main)/register/birthday/page.tsx
Labels: PR status: code ready

#1252 filter fix
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-request-length-with-group.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/mutations/otp/create-otp.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-reqeust-length.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1253 feat: tinder
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Carouselmg.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/functionalities/Swiping.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/heaeder/Header.tsx
  apps/1CD/tinder/frontend/src/graphql/about/getMe.graphql
Labels: PR status: code ready

#1254 feat: room detail dialog
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/_components/GeneralInfoCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/_components/GeneralinfoDialog.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/_components/RoomServiceCard.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/_components/RoomServiceDialog.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/_components/UpcomingBookings.tsx
  apps/1CD/hotel-booking/frontend/src/app/(admin)/room-detail/[id]/page.tsx
Labels: PR status: code ready

#1259 1258 tinderauth fixed
  apps/1CD/tinder/backend/src/resolvers/index.ts
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
Labels: PR status: code ready

#1256 feat(hotel-booking-frontend): client cancel-booking button hover and …
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/cancel-booking/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/cancel-booking/[id]/page.tsx
Labels: PR status: code ready

#1257 supervisor filter fix and toast for admin
  apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
  apps/1CD/leave-request/frontend/src/app/(main)/admin/page.tsx
  apps/1CD/leave-request/frontend/src/app/(main)/employeeList/page.tsx
  apps/1CD/leave-request/frontend/src/components/admin/CreateEmployeeModal.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestHeader.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/Requests.tsx
  apps/1CD/leave-request/frontend/src/graphql/supervisor.graphql
Labels: PR status: code ready

#1262 feat: tinder fixed token again
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
Labels: PR status: code ready

#1264 feat: tinder-fixed
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
Labels: PR status: code ready

#1233 feat(concert-frontend): frontend
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/TicketDetail.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/PasswordReset.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/order/_components/OrderDetail.tsx
Labels: PR status: code ready, frontend

#1243 1160 event delete frontend
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/AdminDashboardPagination.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputGenreWithLocation.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/AdminDashboardPagination.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboardPagination.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#1266 feat(carousel): carousel detail link done
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/_components/index.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/event/[eventId]/_components/EventDetail.tsx
Labels: PR status: code ready, frontend

#1267 story page & story component on main page
  apps/1CD/instagram/frontend/src/app/(main)/_components/ProgressStyle.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/story/MainPageStory.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/story/SeenStoryCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/story/StoryCarouselCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/story/UnseenStoryCard.tsx
  apps/1CD/instagram/frontend/src/app/home/page.tsx
  apps/1CD/instagram/frontend/src/app/story/[id]/page.tsx
  apps/1CD/instagram/frontend/src/app/story/page.tsx
  apps/1CD/instagram/frontend/src/components/story/BigStoryCard.tsx
  apps/1CD/instagram/frontend/src/components/story/MainPageStory.tsx
  apps/1CD/instagram/frontend/src/graphql/story.graphql
Labels: PR status: code ready

#1272 feat(tinder): env fxed
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
Labels: PR status: code ready

#1277 feat(concert-frontend): order info
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/user-profile/_components/OrderInfo.tsx
Labels: PR status: code ready, frontend

#1222 remove fol
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/remove-follower.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/remove-follower.ts
Labels: PR status: code ready, backend, instagram

#1275 feat(hotel-booking-backend): add amenities changes
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/hotel/add-amenity.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/add-amenity.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/index.ts
  apps/1CD/hotel-booking/backend/src/schemas/amenities.schema.ts
  apps/1CD/hotel-booking/backend/src/schemas/index.ts
Labels: PR status: code ready

#1285 1176 hotel booking hotel detail final
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(user)/(public)/page.tsx
Labels: PR status: code ready, frontend

#1282 feat(concert-frontend): admin-home-design
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/page.tsx
Labels: PR status: code ready

#1290 feat: tinder trying to fix auth
  apps/1CD/tinder/backend/src/handler.ts
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
Labels: PR status: code ready

#1292 notify dotor pro image hervee null bval default zuragtai boloh
  apps/1CD/instagram/frontend/src/app/(main)/_components/notification/index.tsx
Labels: PR status: code ready, frontend, instagram

#1296 feat: tinder
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
Labels: PR status: code ready

#1297 feat: room info update mutation
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/room/update-room.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/room/update-room.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#1287 remove follower in backend
  apps/1CD/instagram/frontend/specs/components/post/UpdateImagesStep1.spec.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/follow/RemoveFollow.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/post/PostImgCard.tsx
  apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
  apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
  apps/1CD/instagram/frontend/src/components/post/PostWithComments.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep1.tsx
  apps/1CD/instagram/frontend/src/components/post/UpdateImagesStep2.tsx
  apps/1CD/instagram/frontend/src/components/user-profile/ChangeProImg.tsx
Labels: PR status: code ready, frontend, instagram

#1302 feat: tidner
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
Labels: PR status: code ready

#1202 feat: get all request
  apps/1CD/leave-request/backend/project.json
  apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-all-requests-leave-calendar.spec.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-request-leave-calendar.ts
  apps/1CD/leave-request/backend/src/resolvers/queries/request/index.ts
  apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Labels: PR status: code ready

#1298 request length front
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
Labels: PR status: code ready

#1307 feat: fds
  apps/1CD/tinder/backend/next.config.js
Labels: PR status: code ready

#1305 1303 tinder profile update front
  apps/1CD/tinder/frontend/cypress/e2e/(main)/profile/profile.cy.tsx
  apps/1CD/tinder/frontend/cypress/e2e/(public)/profile/profile-swap.cy.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/GenderSelect.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/InterstSelect.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/ProfileHeader.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/_feature/TabNavigation.tsx
  apps/1CD/tinder/frontend/src/app/(main)/profile/page.tsx
Labels: PR status: code ready

#1310 notification isview mutation
  apps/1CD/instagram/backend/specs/resolvers/mutations/notifications/view-notify.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/notifications/view-notify.ts
  apps/1CD/instagram/backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, backend, instagram

#1309 feat(concert-backend): update user role
  apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/auth/update-user-role.spec.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/index.ts
  apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/auth/update-user-role.ts
  apps/1CD/concert-ticket-booking/backend/src/schemas/auth.schema.ts
Labels: PR status: code ready, backend

#1315 feat: room update mutation fixed
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/room/update-room.spec.ts
  apps/1CD/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#1318 1316 tinder chat ui improvement
  apps/1CD/tinder/backend/src/resolvers/mutations/tinderchat/update-match.ts
  apps/1CD/tinder/frontend/cypress/e2e/(main)/chat/chatid.cy.tsx
  apps/1CD/tinder/frontend/cypress/e2e/(main)/chat/chatpage.cy.tsx
  apps/1CD/tinder/frontend/src/app/(main)/chat/[id]/page.tsx
  apps/1CD/tinder/frontend/src/app/(main)/chat/page.tsx
  apps/1CD/tinder/frontend/src/app/(main)/recs/_components/match/Match.tsx
  apps/1CD/tinder/frontend/src/app/layout.tsx
  apps/1CD/tinder/frontend/src/components/Chatcontent.tsx
  apps/1CD/tinder/frontend/src/components/Chatdate.tsx
  apps/1CD/tinder/frontend/src/components/Chatloadingerror.tsx
  apps/1CD/tinder/frontend/src/components/Chatmessages.tsx
  apps/1CD/tinder/frontend/src/components/Chatpart.tsx
  apps/1CD/tinder/frontend/src/components/Chatsidebar.tsx
  apps/1CD/tinder/frontend/src/components/Dialog.tsx
  apps/1CD/tinder/frontend/src/components/Loader.tsx
  apps/1CD/tinder/frontend/src/components/Matches.tsx
  apps/1CD/tinder/frontend/src/components/Oneuser.tsx
  apps/1CD/tinder/frontend/src/components/Userdetails.tsx
  apps/1CD/tinder/frontend/src/components/UserdetailsBio.tsx
  apps/1CD/tinder/frontend/src/components/UserdetailsName.tsx
  apps/1CD/tinder/frontend/src/components/UserdetailsProfession.tsx
  apps/1CD/tinder/frontend/src/components/UserdetailsSchool.tsx
  apps/1CD/tinder/frontend/src/components/providers/ApolloWrapper.tsx
  apps/1CD/tinder/frontend/src/components/providers/MatchProvider.tsx
  apps/1CD/tinder/frontend/src/components/providers/OneuserProvider.tsx
  apps/1CD/tinder/frontend/src/components/providers/UserContext.tsx
  apps/1CD/tinder/frontend/src/components/providers/UserDetailsProvider.tsx
Labels: PR status: code ready

#1320 feat(hotel-booking-frontend): profile page frontend and test
  apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/profile/index.cy.tsx
  apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/ContactInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/CountryCodeInput.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/DateOfBirthDatePicker.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/EmergencyInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/PersonalInfo.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/ProfileHeader.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/SecurityAndSettings.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/UpdateProfile.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/profile/page.tsx
Labels: PR status: code ready, frontend

#1324 fix(hotel-booking-project-json): deploy Prod fixed
  apps/1CD/hotel-booking/frontend/project.json
Labels: PR status: code ready, frontend

#1326 feat: tinder
  apps/1CD/tinder/backend/src/resolvers/index.ts
Labels: PR status: code ready

#1330 feat(concert-frontend): admin profile
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/admin-profile/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminHeader.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/admin-profile/_components/AdminInfo.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/admin-profile/page.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend

#1331 feat: tinder
  apps/1CD/tinder/backend/specs/resolvers/mutations/user/check-email.spec.ts
  apps/1CD/tinder/backend/specs/utils/user/otp-expiration.spec.ts
  apps/1CD/tinder/backend/src/models/user/user.model.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/check-email.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/register-with-email.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/resend-otp.ts
  apps/1CD/tinder/backend/src/resolvers/mutations/user/update-user.ts
  apps/1CD/tinder/backend/src/schemas/user/user.schema.ts
  apps/1CD/tinder/backend/src/utils/for-dev-token.ts
  apps/1CD/tinder/backend/src/utils/for-prod-token.ts
  apps/1CD/tinder/backend/src/utils/user/check-otp-expiration.ts
Labels: PR status: code ready

#1327 1313 ig fe notification sortloh bolon viewed iin bg tsagaan boloh
  apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyFollowReqCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyPostLikeCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/notification/index.tsx
  apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#1329 added recent searches to search component
  apps/1CD/instagram/frontend/cypress/e2e/(main)/SearchComponent.cy.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/SearchComponent.tsx
  apps/1CD/instagram/frontend/src/components/providers/UserProvider.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready

#1304 limits from makin request when it reaches limit
  apps/1CD/leave-request/frontend/cypress/e2e/(main)/(main)/create-request.cy.tsx
  apps/1CD/leave-request/frontend/src/components/createNewRequest/CreateNewRequest.tsx
  apps/1CD/leave-request/frontend/src/components/createNewRequest/SelectType.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/DatePicker.tsx
  apps/1CD/leave-request/frontend/src/components/myreq/SentRequest.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestHeader.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/RequestList.tsx
  apps/1CD/leave-request/frontend/src/components/supervisor/Requests.tsx
Labels: PR status: code ready

#1337 feat(concert-backend): schema artist
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
Labels: PR status: code ready

#1335 1278 mobile menu edit
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/sign-in/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/specs/components/layout/header.spec.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/_components/header/Header.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/layout.tsx
Labels: PR status: code ready, frontend

#1340 follow req iig modeloos followerId aar haih bolgoson
  apps/1CD/instagram/backend/specs/resolvers/mutations/follow/confirm-follow-req.spec.ts
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/confirm-follow-req.ts
  apps/1CD/instagram/backend/src/schemas/follow.schema.ts
Labels: PR status: code ready, backend, instagram

#1343 feat(hotel-booking-frontend): profile Page Security and settings
  apps/1CD/hotel-booking/frontend/src/app/(user)/(auth)/_components/Login.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/HeaderCheckout.tsx
  apps/1CD/hotel-booking/frontend/src/app/(user)/(client)/_components/SecurityAndSettings.tsx
  apps/1CD/hotel-booking/frontend/src/components/providers/Header.tsx
Labels: PR status: code ready, frontend

#1346 feat(header): search input hide done
  apps/1CD/concert-ticket-booking/frontend/src/app/user/home/_components/header/Header.tsx
Labels: PR status: code ready, frontend

#1350 be
  apps/1CD/instagram/backend/src/resolvers/mutations/follow/confirm-follow-req.ts
Labels: PR status: code ready, backend, instagram

#1359 1334 ig fe notificationaas confirm hiih
  apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyFollowReqCard.tsx
  apps/1CD/instagram/frontend/src/app/(main)/_components/notification/index.tsx
  apps/1CD/instagram/frontend/src/graphql/all.graphql
Labels: PR status: code ready, frontend, instagram

#1362 feat(hotel-booking-backend): update hotel mutation
  apps/1CD/hotel-booking/backend/specs/resolvers/mutations/hotel/update-hotel-general-info.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/index.ts
  apps/1CD/hotel-booking/backend/src/resolvers/mutations/hotel/update-hotel-general-info.ts
  apps/1CD/hotel-booking/backend/src/schemas/hotels.schema.ts
Labels: PR status: code ready

#1352 feat(concert-frontend): fix
  apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/AdminDashboardPagination.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/EditingDialog.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/admin/components/InputImageEditing.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/cypress/e2e/user/payment/[id]/index.cy.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/AdminDashboard.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/EditingDialog.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/InputImageEditing.tsx
  apps/1CD/concert-ticket-booking/frontend/src/app/admin/home/_components/TimePicker.tsx
  apps/1CD/concert-ticket-booking/frontend/src/graphql/event.graphql
  apps/1CD/concert-ticket-booking/frontend/src/utils/validation-schema.ts
Labels: PR status: code ready

#1356 feat(hotel-booking-backend): getUser resolver schema ynzlav
  apps/1CD/hotel-booking/backend/specs/resolvers/queries/users/get-user.spec.ts
  apps/1CD/hotel-booking/backend/src/resolvers/queries/users/get-user.ts
  apps/1CD/hotel-booking/backend/src/schemas/user.schema.ts
Labels: PR status: code ready, frontend
